# -*- encoding: utf-8 -*-
User.create(:name => 'Bartosz Cytrowski')
User.create(:name => 'Marek Klimowicz')
User.create(:name => 'Dawid Dziadkiewicz')
User.create(:name => 'Łukasz Domaradzki')
User.create(:name => 'Paweł Gościcki')
User.create(:name => 'Jakub Naliwajek')

Pitch.create(:name => "E-warranty", :description => "mobile application scanning receipts and automatically creating product list with warranty information.")
Pitch.create(:name => "FitsU", :description => "mobile application that finds clothes simply fitting you!")
Pitch.create(:name => "Foody", :description => "application for info-kiosks located in hipermarkets (Tesco, etc.) showing to customers only recipes filtered by their prices/cooking time/ingredients criteria.")
Pitch.create(:name => "FitTheKit", :description => "easy way to create your kitchen plan in 3D.")
Pitch.create(:name => "U.Promised", :description => "easily create a short-term reminder in only 5 second & with 3 clicks.")
Pitch.create(:name => "4 Blood Type", :description => "mobile application that helps people eat healthy and accordingly with their blood type.")
Pitch.create(:name => "Salelo", :description => "mobile application that helps you find and share infos about promotions and sales in your neighbourhood.")
Pitch.create(:name => "Pitch & Go", :description => "magic solution to improve organizing Startup Weekends and similar events.")
